### ISSUE TITLE
Track the entire window instead of a specific element

### ISSUE THREAD

**Issue by dd8888** [everweij/solid-boundaries#1]
Hi! Is there a way to track the entire window instead of a specific element? I want to handle window resizing globally not on a single component, after reading the docs I'm not sure if that's possible. 
Thanks!

**Comment by everweij** [comment]
Hi, thanks for reaching out!
This lib is indeed mainly focussed on specific elements.
It depends on your use-case, but you could wrap your app in a `div` with `height: 100vh; width: 100vw;` and track this element to get the dimensions of the inner-window.

Alternatively you can create such a tracking mechanism in a few lines of code -> [see example here](https://playground.solidjs.com/?version=1.3.13#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfr2ZCouOAGU0Ac2hqsvAILMrGR0jL60EACyDBC4YRAAwmpwUBD0hFKy8ooqdBraehZWVhgujDJQrLwAQtEiZPxWvLy4tISIvKkwJuKWEE1JMrjtnd2MvU2MngAWQx30XT2NvCa0uC0ww-Oj47yGmrhTmwtjS1Nw07MjixCSRRDM4WR8cJwENfSi9QC8DX3Nre0AAxYJYDWbApaTDwzIEgv4rNYKWFLPYiA7Iv5nC4YyS9KwyD7MXBocLLWpkABiWQA6hgRLRDAAKACU7Xen1+TX0+lkUDUahMFQA1rJuLxXK4AEpLNAyXiMgjEWhyvaiBm8L6a5RgD5iGQYOAiFTMzlNQRwXBMPovQhvck7W4QJYPCBPewYCDiWloqa+D3iAAS52hfGkP1V9MMeL+QktjD6ICWTRabV4EL+-TggwxZsE2N4-sY3oOcNzCPW7ULQYupbNqPRBYgnqL+19Sd4WJDlabgeDM1ruKsjvxhOJpNwjGFtLVhnZdRZ7QCQRCAB452QAHyml1u4ArXVkXxkC3rgC6GocThc7i8fMZ+8+VIU08jLOZ0a5PIAKmdtVARCIACiABuwi4AAMmgTzCOIKiCAwLjOo8fBTCkIhJJKcBkGgABecAXiyGpbseuDrve5JPjAL4Mm+OzhFEHy4IyhFfFuEYMgAdP+QGgTEkHQc2jIqEI2F4SovioaIGFYbhcDMu+SzhIkySpIQzEmqxux0pxQgwLQoEgWB-EuIJwkyWJ2Admh0miXJClOn83K8D++EqJhtkAPImMejCgYwcHyPQiGOTyO58LQ3niH5F6eoYvDubJXk+X56lEbwJFkQ+dSUdRTLyfZn68PR0RMSxW4Rcl4gcRVUVwIy9LMPMYEcSsIj4PJOxOUpSQpGkqWaTVvlVSIUEup6RK0XcEwWlaZIHr0w4QAS9xjn0fiEGpJqJn8YVzRyPwTlO2mzuSLIfuacZ9EJGa8CuI3ARu7ZNHdaAPfETBCDEWkzntdSICu+j3Y9N3PYQQjA7muYrg8YgbiAABSrgeQAchxTyTBAHiyvg5EHiyvipPyvgACzMpIAMw3AEOQwDYNU+2ANA0s9mLZ9YiMP1W4rut6T6BuvgNU1MQcR4FqAUk8AxFU+AAJIiEJYBQBtxr2WAkinkAA)
